### ISSUE TITLE
Simplify the CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [manok2912/prj-rev-bwfs-dasmoto#8]
It is a good idea to try and simplify the CSS code to make the code cleaner and to remove repetitive code. You can do this by applying shared properties to multiple elements at once, rather than individually. Some properties that are shared in the document for all elements are the font-family and font-weight properties. You can simplify this by applying it to each element individually, or by the parent element, like

```css
h1, .sh, span {
  font-family: Helvetica;
  font-weight: bold;
}
```
or
```css
body {
  font-family: Helvetica;
  font-weight: bold;
}
```
